### ISSUE TITLE
Custom Speedometer Customization

### ISSUE THREAD

**Issue by ShatteredDarkrai** [LunaXCBN/RenHud-V2#17]
Requesting support for a Speedometer customization (https://gamebanana.com/mods/378554) with a fitting style, somewhat like Hypnotize Hud (https://
github.com/Hypnootize/hypnotize-hud/)

**Comment by ShatteredDarkrai** [comment]
Sorry for no tags, my guihub mobile broke! Will be added soon.

**Comment by LunaXCBN** [comment]
Added, will be available next update
