### ISSUE TITLE
4:3 NOT WORKING 

### ISSUE THREAD

**Issue by warhit04** [LunaXCBN/RenHud-V2#19]
![image](https://user-images.githubusercontent.com/120324046/206912753-6783d9fb-c4c2-4d98-985d-ff987cc8c8c6.png)

**Comment by LunaXCBN** [comment]
Do you have it enabled from customization/resolutions?
You need to remove the "_" from the folder for it to work. If that doesn't work, I'll look into it

**Comment by LunaXCBN** [comment]
Non-issue, closed.
